Python3 (#24)
* Translate to Python3 (using 2to3)

+ add .gitignore

* Adhere to (flake8) style guide

* Fix various wx errors:

+ FlexGridSizer(): arguments did not match any overloaded call
+ Sizer.Remove(): arguments did not match any overloaded call
+ 'Menu' object has no attribute 'DeleteItem'

* Fix config type error

TypeError: a bytes-like object is required, not 'str'

* Fix type error:

TypeError: startswith first arg must be bytes or a tuple of bytes, not str

* Revert inadvertently removed 'object' class

* Fix about dialog

AttributeError: module 'wx' has no attribute 'AboutDialogInfo'

* Python3 required

* wxPython 4 required

* Fix wx error

+ Vertical alignment flags are ignored in vertical sizers

* Fix error: Exception object has no attribute 'message'

* Fix binary STLs not read

* Adhere to (flake8) style guide

* Remove obsolete unit test

+ fix new layer from z, as it depends on e too

* Fix deprecated class warning